name: Recent Blog Posts Update

on:
  schedule:
    # KST 22:00, 22:30, 23:00, 23:30
    - cron: '0,30 13,14 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: https://kingpiggylab.tistory.com/rss
          max_post_count: 5
